### ISSUE TITLE
exitBeforeEnter deprecated, must replace with mode='wait'

### ISSUE THREAD

**Issue by Amanda-LillyFunds** [UgnisSoftware/react-spreadsheet-import#159]
When using ReactSpreadsheetImport I received the following error:

Uncaught Error: Replace exitBeforeEnter with mode='wait'
    at invariant (errors.mjs:19:19)
    at AnimatePresence (index.mjs:73:65)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20069:13)
    at beginWork (react-dom.development.js:21582:16)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27446:7)
    at performUnitOfWork (react-dom.development.js:26552:12)

**Comment by Amanda-LillyFunds** [comment]
Solved the issues by using "yarn remove framer-motion" so I could add this specific version:

yarn add framer-motion@4.1.17

**Comment by thenano** [comment]
I can also confirm that react-spreadsheet-importer no longer works with frame-motion > 9 because exitBeforeEnter was removed in framer-motion 10

**Comment by masiulis** [comment]
Sorry for a late reply, this should be less of an issue as we have added framer-motion v7 to our dependencies (because we depend on a package `chakra-ui-steps` that has this specific version locked). Please open a new issue if it's still a problem with react-spreadsheet-import >4.0.0.

**Comment by thenano** [comment]
Hi @masiulis thanks for this, I can confirm that adding framer-motion as a dependency is no longer required.
